# Generated by Django 3.2.7 on 2021-10-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lang',
            field=models.CharField(choices=[['Turkmen', 'Turkmen'], ['English', 'English']], default='Turkmen', max_length=255, verbose_name='Lang'),
        ),
    ]
